Linting rules
CGnal/python-ci-template pull request #30
Opened 2022-01-25 14:27 UTC by aiola

Resolves #13

2022-01-25 14:55 UTC, deusebio commented on .mypy.ini
> +ignore_missing_imports = True
Bellissimo! But does this mean that we can skip the " # type: ignore" everywhere in the code (v. cgnal-core)?

2022-01-25 14:55 UTC, deusebio approved these changes
Looks good!

2022-01-27 11:14 UTC, NicolaDonelli approved these changes
Wouldn't it be possible to move all the configuration files in the confs folder?
Are there checks on presence of docstrings on every object?

Except for that minor detail, I am fine with the content.

2022-01-27 11:23 UTC, NicolaDonelli requested changes

2022-01-27 11:23 UTC, NicolaDonelli commented on .flake8
> +select = B,C,E,F,W,T4,B9
It would be better to include this section in the setup.cfg file

2022-01-27 11:25 UTC, NicolaDonelli commented on .mypy.ini
> +ignore_missing_imports = True
Couldn't this file be included as a section in the `setup.cfg` file?

2022-01-31 10:32 UTC, NicolaDonelli approved these changes

2022-01-31 10:48 UTC, merged